name: ci

on: [push, pull_request]

jobs:
  test-front:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm i
      working-directory: ./web-client
    - name: Run tests
      run: npm test
      working-directory: ./web-client
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: npm run lint-action 
